[package]
name = "slambda-core"
version = "0.1.0"
edition = "2021"
description = "Rust implementation of the SΛ framework for semantic universes"
authors = ["SΛ Team"]

[dependencies]
tracing = "0.1"
thiserror = "1.0"
derive_more = "0.99"

[dev-dependencies]
tracing-subscriber = "0.3"
